trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: terraforming
    jobs:
      - job: terraform
        steps:
        - task: TerraformInstaller@1
          displayName: terraformInstall
          inputs:
            terraformVersion: '1.4.6'
        - task: TerraformTaskV4@4
          displayName: terraformInit
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'version-1(32f8356a-aee0-4b56-804a-2e56a7ea610c)'
            backendAzureRmResourceGroupName: 'this_rg'
            backendAzureRmStorageAccountName: 'betav1project'
            backendAzureRmContainerName: 'terraformstatefile'
            backendAzureRmKey: 'test.tfstate'
        - task: TerraformTaskV4@4
          displayName: terrafomValidate
          inputs:
            provider: 'azurerm'
            command: 'validate'
